<?php

namespace Database\Seeders\Share;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {


        $timestamp = Carbon::now()->toDateTimeString();

        $countries = [
            [
                "code" => "AF",
                "name" => "Afghanistan",
                "phone_code" => "+93",
                "latitude" => 33.93911,
                "longitude" => 67.709953,
            ],
            [
                "code" => "AX",
                "name" => "Aland Islands",
                "phone_code" => "+358",
                "latitude" => 60.1785,
                "longitude" => 19.9156,
            ],
            [
                "code" => "AL",
                "name" => "Albania",
                "phone_code" => "+355",
                "latitude" => 41.153332,
                "longitude" => 20.168331,
            ],
            [
                "code" => "DZ",
                "name" => "Algeria",
                "phone_code" => "+213",
                "latitude" => 28.033886,
                "longitude" => 1.659626,
            ],
            [
                "code" => "AS",
                "name" => "AmericanSamoa",
                "phone_code" => "+1684",
                "latitude" => -14.270972,
                "longitude" => -170.132217,
            ],
            [
                "code" => "AD",
                "name" => "Andorra",
                "phone_code" => "+376",
                "latitude" => 42.546245,
                "longitude" => 1.601554,
            ],
            [
                "code" => "AO",
                "name" => "Angola",
                "phone_code" => "+244",
                "latitude" => -11.202692,
                "longitude" => 17.873887,
            ],
            [
                "code" => "AI",
                "name" => "Anguilla",
                "phone_code" => "+1264",
                "latitude" => 18.220554,
                "longitude" => -63.068615,
            ],
            [
                "code" => "AQ",
                "name" => "Antarctica",
                "phone_code" => "+672",
                "latitude" => -75.250973,
                "longitude" => -0.071389,
            ],
            [
                "code" => "AG",
                "name" => "Antigua and Barbuda",
                "phone_code" => "+1268",
                "latitude" => 17.060816,
                "longitude" => -61.796428,
            ],
            [
                "code" => "AR",
                "name" => "Argentina",
                "phone_code" => "+54",
                "latitude" => -38.416097,
                "longitude" => -63.616672,
            ],
            [
                "code" => "AM",
                "name" => "Armenia",
                "phone_code" => "+374",
                "latitude" => 40.069099,
                "longitude" => 45.038189,
            ],
            [
                "code" => "AW",
                "name" => "Aruba",
                "phone_code" => "+297",
                "latitude" => 12.52111,
                "longitude" => -69.968338,
            ],
            [
                "code" => "AU",
                "name" => "Australia",
                "phone_code" => "+61",
                "latitude" => -25.274398,
                "longitude" => 133.775136,
            ],
            [
                "code" => "AT",
                "name" => "Austria",
                "phone_code" => "+43",
                "latitude" => 47.516231,
                "longitude" => 14.550072,
            ],
            [
                "code" => "AZ",
                "name" => "Azerbaijan",
                "phone_code" => "+994",
                "latitude" => 40.143105,
                "longitude" => 47.576927,
            ],
            [
                "code" => "BS",
                "name" => "Bahamas",
                "phone_code" => "+1242",
                "latitude" => 25.03428,
                "longitude" => -77.39628,
            ],
            [
                "code" => "BH",
                "name" => "Bahrain",
                "phone_code" => "+973",
                "latitude" => 25.930414,
                "longitude" => 50.637772,
            ],
            [
                "code" => "BD",
                "name" => "Bangladesh",
                "phone_code" => "+880",
                "latitude" => 23.684994,
                "longitude" => 90.356331,
            ],
            [
                "code" => "BB",
                "name" => "Barbados",
                "phone_code" => "+1246",
                "latitude" => 13.193887,
                "longitude" => -59.543198,
            ],
            [
                "code" => "BY",
                "name" => "Belarus",
                "phone_code" => "+375",
                "latitude" => 53.709807,
                "longitude" => 27.953389,
            ],
            [
                "code" => "BE",
                "name" => "Belgium",
                "phone_code" => "+32",
                "latitude" => 50.503887,
                "longitude" => 4.469936,
            ],
            [
                "code" => "BZ",
                "name" => "Belize",
                "phone_code" => "+501",
                "latitude" => 17.189877,
                "longitude" => -88.49765,
            ],
            [
                "code" => "BJ",
                "name" => "Benin",
                "phone_code" => "+229",
                "latitude" => 9.30769,
                "longitude" => 2.315834,
            ],
            [
                "code" => "BM",
                "name" => "Bermuda",
                "phone_code" => "+1441",
                "latitude" => 32.321384,
                "longitude" => -64.75737,
            ],
            [
                "code" => "BT",
                "name" => "Bhutan",
                "phone_code" => "+975",
                "latitude" => 27.514162,
                "longitude" => 90.433601,
            ],
            [
                "code" => "BO",
                "name" => "Bolivia, Plurinational State of",
                "phone_code" => "+591",
                "latitude" => -16.290154,
                "longitude" => -63.588653,
            ],
            [
                "code" => "BA",
                "name" => "Bosnia and Herzegovina",
                "phone_code" => "+387",
                "latitude" => 43.915886,
                "longitude" => 17.679076,
            ],
            [
                "code" => "BW",
                "name" => "Botswana",
                "phone_code" => "+267",
                "latitude" => -22.328474,
                "longitude" => 24.684866,
            ],
            [
                "code" => "BR",
                "name" => "Brazil",
                "phone_code" => "+55",
                "latitude" => -14.235004,
                "longitude" => -51.92528,
            ],
            [
                "code" => "IO",
                "name" => "British Indian Ocean Territory",
                "phone_code" => "+246",
                "latitude" => -6.343194,
                "longitude" => 71.876519,
            ],
            [
                "code" => "BN",
                "name" => "Brunei Darussalam",
                "phone_code" => "+673",
                "latitude" => 4.535277,
                "longitude" => 114.727669,
            ],
            [
                "code" => "BG",
                "name" => "Bulgaria",
                "phone_code" => "+359",
                "latitude" => 42.733883,
                "longitude" => 25.48583,
            ],
            [
                "code" => "BF",
                "name" => "Burkina Faso",
                "phone_code" => "+226",
                "latitude" => 12.238333,
                "longitude" => -1.561593,
            ],
            [
                "code" => "BI",
                "name" => "Burundi",
                "phone_code" => "+257",
                "latitude" => -3.373056,
                "longitude" => 29.918886,
            ],
            [
                "code" => "KH",
                "name" => "Cambodia",
                "phone_code" => "+855",
                "latitude" => 12.565679,
                "longitude" => 104.990963,
            ],
            [
                "code" => "CM",
                "name" => "Cameroon",
                "phone_code" => "+237",
                "latitude" => 7.369722,
                "longitude" => 12.354722,
            ],
            [
                "code" => "CA",
                "name" => "Canada",
                "phone_code" => "+1",
                "latitude" => 56.130366,
                "longitude" => -106.346771,
            ],
            [
                "code" => "CV",
                "name" => "Cape Verde",
                "phone_code" => "+238",
                "latitude" => 16.002082,
                "longitude" => -24.013197,
            ],
            [
                "code" => "KY",
                "name" => "Cayman Islands",
                "phone_code" => "+ 345",
                "latitude" => 19.513469,
                "longitude" => -80.566956,
            ],
            [
                "code" => "CF",
                "name" => "Central African Republic",
                "phone_code" => "+236",
                "latitude" => 6.611111,
                "longitude" => 20.939444,
            ],
            [
                "code" => "TD",
                "name" => "Chad",
                "phone_code" => "+235",
                "latitude" => 15.454166,
                "longitude" => 18.732207,
            ],
            [
                "code" => "CL",
                "name" => "Chile",
                "phone_code" => "+56",
                "latitude" => -35.675147,
                "longitude" => -71.542969,
            ],
            [
                "code" => "CN",
                "name" => "China",
                "phone_code" => "+86",
                "latitude" => 35.86166,
                "longitude" => 104.195397,
            ],
            [
                "code" => "CX",
                "name" => "Christmas Island",
                "phone_code" => "+61",
                "latitude" => -10.447525,
                "longitude" => 105.690449,
            ],
            [
                "code" => "CC",
                "name" => "Cocos (Keeling) Islands",
                "phone_code" => "+61",
                "latitude" => -12.164165,
                "longitude" => 96.870956,
            ],
            [
                "code" => "CO",
                "name" => "Colombia",
                "phone_code" => "+57",
                "latitude" => 4.570868,
                "longitude" => -74.297333,
            ],
            [
                "code" => "KM",
                "name" => "Comoros",
                "phone_code" => "+269",
                "latitude" => -11.875001,
                "longitude" => 43.872219,
            ],
            [
                "code" => "CG",
                "name" => "Congo",
                "phone_code" => "+242",
                "latitude" => -0.228021,
                "longitude" => 15.827659,
            ],
            [
                "code" => "CD",
                "name" => "Congo, The Democratic Republic of the Congo",
                "phone_code" => "+243",
                "latitude" => -4.038333,
                "longitude" => 21.758664,
            ],
            [
                "code" => "CK",
                "name" => "Cook Islands",
                "phone_code" => "+682",
                "latitude" => -21.236736,
                "longitude" => -159.777671,
            ],
            [
                "code" => "CR",
                "name" => "Costa Rica",
                "phone_code" => "+506",
                "latitude" => 9.748917,
                "longitude" => -83.753428,
            ],
            [
                "code" => "CI",
                "name" => "Cote d\'Ivoire",
                "phone_code" => "+225",
                "latitude" => 7.539989,
                "longitude" => -5.54708,
            ],
            [
                "code" => "HR",
                "name" => "Croatia",
                "phone_code" => "+385",
                "latitude" => 45.1,
                "longitude" => 15.2,
            ],
            [
                "code" => "CU",
                "name" => "Cuba",
                "phone_code" => "+53",
                "latitude" => 21.521757,
                "longitude" => -77.781167,
            ],
            [
                "code" => "CY",
                "name" => "Cyprus",
                "phone_code" => "+357",
                "latitude" => 35.126413,
                "longitude" => 33.429859,
            ],
            [
                "code" => "CZ",
                "name" => "Czech Republic",
                "phone_code" => "+420",
                "latitude" => 49.817492,
                "longitude" => 15.472962,
            ],
            [
                "code" => "DK",
                "name" => "Denmark",
                "phone_code" => "+45",
                "latitude" => 56.26392,
                "longitude" => 9.501785,
            ],
            [
                "code" => "DJ",
                "name" => "Djibouti",
                "phone_code" => "+253",
                "latitude" => 11.825138,
                "longitude" => 42.590275,
            ],
            [
                "code" => "DM",
                "name" => "Dominica",
                "phone_code" => "+1767",
                "latitude" => 15.414999,
                "longitude" => -61.370976,
            ],
            [
                "code" => "DO",
                "name" => "Dominican Republic",
                "phone_code" => "+1849",
                "latitude" => 18.735693,
                "longitude" => -70.162651,
            ],
            [
                "code" => "EC",
                "name" => "Ecuador",
                "phone_code" => "+593",
                "latitude" => -1.831239,
                "longitude" => -78.183406,
            ],
            [
                "code" => "EG",
                "name" => "Egypt",
                "phone_code" => "+20",
                "latitude" => 26.820553,
                "longitude" => 30.802498,
            ],
            [
                "code" => "SV",
                "name" => "El Salvador",
                "phone_code" => "+503",
                "latitude" => 13.794185,
                "longitude" => -88.89653,
            ],
            [
                "code" => "GQ",
                "name" => "Equatorial Guinea",
                "phone_code" => "+240",
                "latitude" => 1.650801,
                "longitude" => 10.267895,
            ],
            [
                "code" => "ER",
                "name" => "Eritrea",
                "phone_code" => "+291",
                "latitude" => 15.179384,
                "longitude" => 39.782334,
            ],
            [
                "code" => "EE",
                "name" => "Estonia",
                "phone_code" => "+372",
                "latitude" => 58.595272,
                "longitude" => 25.013607,
            ],
            [
                "code" => "ET",
                "name" => "Ethiopia",
                "phone_code" => "+251",
                "latitude" => 9.145,
                "longitude" => 40.489673,
            ],
            [
                "code" => "FK",
                "name" => "Falkland Islands (Malvinas)",
                "phone_code" => "+500",
                "latitude" => -51.796253,
                "longitude" => -59.523613,
            ],
            [
                "code" => "FO",
                "name" => "Faroe Islands",
                "phone_code" => "+298",
                "latitude" => 61.892635,
                "longitude" => -6.911806,
            ],
            [
                "code" => "FJ",
                "name" => "Fiji",
                "phone_code" => "+679",
                "latitude" => -16.578193,
                "longitude" => 179.414413,
            ],
            [
                "code" => "FI",
                "name" => "Finland",
                "phone_code" => "+358",
                "latitude" => 61.92411,
                "longitude" => 25.748151,
            ],
            [
                "code" => "FR",
                "name" => "France",
                "phone_code" => "+33",
                "latitude" => 46.227638,
                "longitude" => 2.213749,
            ],
            [
                "code" => "GF",
                "name" => "French Guiana",
                "phone_code" => "+594",
                "latitude" => 3.933889,
                "longitude" => -53.125782,
            ],
            [
                "code" => "PF",
                "name" => "French Polynesia",
                "phone_code" => "+689",
                "latitude" => -17.679742,
                "longitude" => -149.406843,
            ],
            [
                "code" => "GA",
                "name" => "Gabon",
                "phone_code" => "+241",
                "latitude" => -0.803689,
                "longitude" => 11.609444,
            ],
            [
                "code" => "GM",
                "name" => "Gambia",
                "phone_code" => "+220",
                "latitude" => 13.443182,
                "longitude" => -15.310139,
            ],
            [
                "code" => "GE",
                "name" => "Georgia",
                "phone_code" => "+995",
                "latitude" => 42.315407,
                "longitude" => 43.356892,
            ],
            [
                "code" => "DE",
                "name" => "Germany",
                "phone_code" => "+49",
                "latitude" => 51.165691,
                "longitude" => 10.451526,
            ],
            [
                "code" => "GH",
                "name" => "Ghana",
                "phone_code" => "+233",
                "latitude" => 7.946527,
                "longitude" => -1.023194,
            ],
            [
                "code" => "GI",
                "name" => "Gibraltar",
                "phone_code" => "+350",
                "latitude" => 36.137741,
                "longitude" => -5.345374,
            ],
            [
                "code" => "GR",
                "name" => "Greece",
                "phone_code" => "+30",
                "latitude" => 39.074208,
                "longitude" => 21.824312,
            ],
            [
                "code" => "GL",
                "name" => "Greenland",
                "phone_code" => "+299",
                "latitude" => 71.706936,
                "longitude" => -42.604303,
            ],
            [
                "code" => "GD",
                "name" => "Grenada",
                "phone_code" => "+1473",
                "latitude" => 12.262776,
                "longitude" => -61.604171,
            ],
            [
                "code" => "GP",
                "name" => "Guadeloupe",
                "phone_code" => "+590",
                "latitude" => 16.995971,
                "longitude" => -62.067641,
            ],
            [
                "code" => "GU",
                "name" => "Guam",
                "phone_code" => "+1671",
                "latitude" => 13.444304,
                "longitude" => 144.793731,
            ],
            [
                "code" => "GT",
                "name" => "Guatemala",
                "phone_code" => "+502",
                "latitude" => 15.783471,
                "longitude" => -90.230759,
            ],
            [
                "code" => "GG",
                "name" => "Guernsey",
                "phone_code" => "+44",
                "latitude" => 49.465691,
                "longitude" => -2.585278,
            ],
            [
                "code" => "GN",
                "name" => "Guinea",
                "phone_code" => "+224",
                "latitude" => 9.945587,
                "longitude" => -9.696645,
            ],
            [
                "code" => "GW",
                "name" => "Guinea-Bissau",
                "phone_code" => "+245",
                "latitude" => 11.803749,
                "longitude" => -15.180413,
            ],
            [
                "code" => "GY",
                "name" => "Guyana",
                "phone_code" => "+595",
                "latitude" => 4.860416,
                "longitude" => -58.93018,
            ],
            [
                "code" => "HT",
                "name" => "Haiti",
                "phone_code" => "+509",
                "latitude" => 18.971187,
                "longitude" => -72.285215,
            ],
            [
                "code" => "VA",
                "name" => "Holy See (Vatican City State)",
                "phone_code" => "+379",
                "latitude" => 41.902916,
                "longitude" => 12.453389,
            ],
            [
                "code" => "HN",
                "name" => "Honduras",
                "phone_code" => "+504",
                "latitude" => 15.199999,
                "longitude" => -86.241905,
            ],
            [
                "code" => "HK",
                "name" => "Hong Kong",
                "phone_code" => "+852",
                "latitude" => 22.396428,
                "longitude" => 114.109497,
            ],
            [
                "code" => "HU",
                "name" => "Hungary",
                "phone_code" => "+36",
                "latitude" => 47.162494,
                "longitude" => 19.503304,
            ],
            [
                "code" => "IS",
                "name" => "Iceland",
                "phone_code" => "+354",
                "latitude" => 64.963051,
                "longitude" => -19.020835,
            ],
            [
                "code" => "IN",
                "name" => "India",
                "phone_code" => "+91",
                "latitude" => 20.593684,
                "longitude" => 78.96288,
            ],
            [
                "code" => "ID",
                "name" => "Indonesia",
                "phone_code" => "+62",
                "latitude" => -0.789275,
                "longitude" => 113.921327,
            ],
            [
                "code" => "IR",
                "name" => "Iran, Islamic Republic of Persian Gulf",
                "phone_code" => "+98",
                "latitude" => 32.427908,
                "longitude" => 53.688046,
            ],
            [
                "code" => "IQ",
                "name" => "Iraq",
                "phone_code" => "+964",
                "latitude" => 33.223191,
                "longitude" => 43.679291,
            ],
            [
                "code" => "IE",
                "name" => "Ireland",
                "phone_code" => "+353",
                "latitude" => 53.41291,
                "longitude" => -8.24389,
            ],
            [
                "code" => "IM",
                "name" => "Isle of Man",
                "phone_code" => "+44",
                "latitude" => 54.236107,
                "longitude" => -4.548056,
            ],
            [
                "code" => "IL",
                "name" => "Israel",
                "phone_code" => "+972",
                "latitude" => 31.046051,
                "longitude" => 34.851612,
            ],
            [
                "code" => "IT",
                "name" => "Italy",
                "phone_code" => "+39",
                "latitude" => 41.87194,
                "longitude" => 12.56738,
            ],
            [
                "code" => "JM",
                "name" => "Jamaica",
                "phone_code" => "+1876",
                "latitude" => 18.109581,
                "longitude" => -77.297508,
            ],
            [
                "code" => "JP",
                "name" => "Japan",
                "phone_code" => "+81",
                "latitude" => 36.204824,
                "longitude" => 138.252924,
            ],
            [
                "code" => "JE",
                "name" => "Jersey",
                "phone_code" => "+44",
                "latitude" => 49.214439,
                "longitude" => -2.13125,
            ],
            [
                "code" => "JO",
                "name" => "Jordan",
                "phone_code" => "+962",
                "latitude" => 30.585164,
                "longitude" => 36.238414,
            ],
            [
                "code" => "KZ",
                "name" => "Kazakhstan",
                "phone_code" => "+77",
                "latitude" => 48.019573,
                "longitude" => 66.923684,
            ],
            [
                "code" => "KE",
                "name" => "Kenya",
                "phone_code" => "+254",
                "latitude" => -0.023559,
                "longitude" => 37.906193,
            ],
            [
                "code" => "KI",
                "name" => "Kiribati",
                "phone_code" => "+686",
                "latitude" => -3.370417,
                "longitude" => -168.734039,
            ],
            [
                "code" => "KP",
                "name" => "Korea, Democratic People\'s Republic of Korea",
                "phone_code" => "+850",
                "latitude" => 40.339852,
                "longitude" => 127.510093,
            ],
            [
                "code" => "KR",
                "name" => "Korea, Republic of South Korea",
                "phone_code" => "+82",
                "latitude" => 35.907757,
                "longitude" => 127.766922,
            ],
            [
                "code" => "KW",
                "name" => "Kuwait",
                "phone_code" => "+965",
                "latitude" => 29.31166,
                "longitude" => 47.481766,
            ],
            [
                "code" => "KG",
                "name" => "Kyrgyzstan",
                "phone_code" => "+996",
                "latitude" => 41.20438,
                "longitude" => 74.766098,
            ],
            [
                "code" => "LA",
                "name" => "Laos",
                "phone_code" => "+856",
                "latitude" => 19.85627,
                "longitude" => 102.495496,
            ],
            [
                "code" => "LV",
                "name" => "Latvia",
                "phone_code" => "+371",
                "latitude" => 56.879635,
                "longitude" => 24.603189,
            ],
            [
                "code" => "LB",
                "name" => "Lebanon",
                "phone_code" => "+961",
                "latitude" => 33.854721,
                "longitude" => 35.862285,
            ],
            [
                "code" => "LS",
                "name" => "Lesotho",
                "phone_code" => "+266",
                "latitude" => -29.609988,
                "longitude" => 28.233608,
            ],
            [
                "code" => "LR",
                "name" => "Liberia",
                "phone_code" => "+231",
                "latitude" => 6.428055,
                "longitude" => -9.429499,
            ],
            [
                "code" => "LY",
                "name" => "Libyan Arab Jamahiriya",
                "phone_code" => "+218",
                "latitude" => 26.3351,
                "longitude" => 17.228331,
            ],
            [
                "code" => "LI",
                "name" => "Liechtenstein",
                "phone_code" => "+423",
                "latitude" => 47.166,
                "longitude" => 9.555373,
            ],
            [
                "code" => "LT",
                "name" => "Lithuania",
                "phone_code" => "+370",
                "latitude" => 55.169438,
                "longitude" => 23.881275,
            ],
            [
                "code" => "LU",
                "name" => "Luxembourg",
                "phone_code" => "+352",
                "latitude" => 49.815273,
                "longitude" => 6.129583,
            ],
            [
                "code" => "MO",
                "name" => "Macao",
                "phone_code" => "+853",
                "latitude" => 22.198745,
                "longitude" => 113.543873,
            ],
            [
                "code" => "MK",
                "name" => "Macedonia",
                "phone_code" => "+389",
                "latitude" => 41.608635,
                "longitude" => 21.745275,
            ],
            [
                "code" => "MG",
                "name" => "Madagascar",
                "phone_code" => "+261",
                "latitude" => -18.766947,
                "longitude" => 46.869107,
            ],
            [
                "code" => "MW",
                "name" => "Malawi",
                "phone_code" => "+265",
                "latitude" => -13.254308,
                "longitude" => 34.301525,
            ],
            [
                "code" => "MY",
                "name" => "Malaysia",
                "phone_code" => "+60",
                "latitude" => 4.210484,
                "longitude" => 101.975766,
            ],
            [
                "code" => "MV",
                "name" => "Maldives",
                "phone_code" => "+960",
                "latitude" => 3.202778,
                "longitude" => 73.22068,
            ],
            [
                "code" => "ML",
                "name" => "Mali",
                "phone_code" => "+223",
                "latitude" => 17.570692,
                "longitude" => -3.996166,
            ],
            [
                "code" => "MT",
                "name" => "Malta",
                "phone_code" => "+356",
                "latitude" => 35.937496,
                "longitude" => 14.375416,
            ],
            [
                "code" => "MH",
                "name" => "Marshall Islands",
                "phone_code" => "+692",
                "latitude" => 7.131474,
                "longitude" => 171.184478,
            ],
            [
                "code" => "MQ",
                "name" => "Martinique",
                "phone_code" => "+596",
                "latitude" => 14.641528,
                "longitude" => -61.024174,
            ],
            [
                "code" => "MR",
                "name" => "Mauritania",
                "phone_code" => "+222",
                "latitude" => 21.00789,
                "longitude" => -10.940835,
            ],
            [
                "code" => "MU",
                "name" => "Mauritius",
                "phone_code" => "+230",
                "latitude" => -20.348404,
                "longitude" => 57.552152,
            ],
            [
                "code" => "YT",
                "name" => "Mayotte",
                "phone_code" => "+262",
                "latitude" => -12.8275,
                "longitude" => 45.166244,
            ],
            [
                "code" => "MX",
                "name" => "Mexico",
                "phone_code" => "+52",
                "latitude" => 23.634501,
                "longitude" => -102.552784,
            ],
            [
                "code" => "FM",
                "name" => "Micronesia, Federated States of Micronesia",
                "phone_code" => "+691",
                "latitude" => 7.425554,
                "longitude" => 150.550812,
            ],
            [
                "code" => "MD",
                "name" => "Moldova",
                "phone_code" => "+373",
                "latitude" => 47.411631,
                "longitude" => 28.369885,
            ],
            [
                "code" => "MC",
                "name" => "Monaco",
                "phone_code" => "+377",
                "latitude" => 43.750298,
                "longitude" => 7.412841,
            ],
            [
                "code" => "MN",
                "name" => "Mongolia",
                "phone_code" => "+976",
                "latitude" => 46.862496,
                "longitude" => 103.846656,
            ],
            [
                "code" => "ME",
                "name" => "Montenegro",
                "phone_code" => "+382",
                "latitude" => 42.708678,
                "longitude" => 19.37439,
            ],
            [
                "code" => "MS",
                "name" => "Montserrat",
                "phone_code" => "+1664",
                "latitude" => 16.742498,
                "longitude" => -62.187366,
            ],
            [
                "code" => "MA",
                "name" => "Morocco",
                "phone_code" => "+212",
                "latitude" => 31.791702,
                "longitude" => -7.09262,
            ],
            [
                "code" => "MZ",
                "name" => "Mozambique",
                "phone_code" => "+258",
                "latitude" => -18.665695,
                "longitude" => 35.529562,
            ],
            [
                "code" => "MM",
                "name" => "Myanmar",
                "phone_code" => "+95",
                "latitude" => 21.913965,
                "longitude" => 95.956223,
            ],
            [
                "code" => "NA",
                "name" => "Namibia",
                "phone_code" => "+264",
                "latitude" => -22.95764,
                "longitude" => 18.49041,
            ],
            [
                "code" => "NR",
                "name" => "Nauru",
                "phone_code" => "+674",
                "latitude" => -0.522778,
                "longitude" => 166.931503,
            ],
            [
                "code" => "NP",
                "name" => "Nepal",
                "phone_code" => "+977",
                "latitude" => 28.394857,
                "longitude" => 84.124008,
            ],
            [
                "code" => "NL",
                "name" => "Netherlands",
                "phone_code" => "+31",
                "latitude" => 52.132633,
                "longitude" => 5.291266,
            ],
            [
                "code" => "AN",
                "name" => "Netherlands Antilles",
                "phone_code" => "+599",
                "latitude" => 12.226079,
                "longitude" => -69.060087,
            ],
            [
                "code" => "NC",
                "name" => "New Caledonia",
                "phone_code" => "+687",
                "latitude" => -20.904305,
                "longitude" => 165.618042,
            ],
            [
                "code" => "NZ",
                "name" => "New Zealand",
                "phone_code" => "+64",
                "latitude" => -40.900557,
                "longitude" => 174.885971,
            ],
            [
                "code" => "NI",
                "name" => "Nicaragua",
                "phone_code" => "+505",
                "latitude" => 12.865416,
                "longitude" => -85.207229,
            ],
            [
                "code" => "NE",
                "name" => "Niger",
                "phone_code" => "+227",
                "latitude" => 17.607789,
                "longitude" => 8.081666,
            ],
            [
                "code" => "NG",
                "name" => "Nigeria",
                "phone_code" => "+234",
                "latitude" => 9.081999,
                "longitude" => 8.675277,
            ],
            [
                "code" => "NU",
                "name" => "Niue",
                "phone_code" => "+683",
                "latitude" => -19.054445,
                "longitude" => -169.867233,
            ],
            [
                "code" => "NF",
                "name" => "Norfolk Island",
                "phone_code" => "+672",
                "latitude" => -29.040835,
                "longitude" => 167.954712,
            ],
            [
                "code" => "MP",
                "name" => "Northern Mariana Islands",
                "phone_code" => "+1670",
                "latitude" => 17.33083,
                "longitude" => 145.38469,
            ],
            [
                "code" => "NO",
                "name" => "Norway",
                "phone_code" => "+47",
                "latitude" => 60.472024,
                "longitude" => 8.468946,
            ],
            [
                "code" => "OM",
                "name" => "Oman",
                "phone_code" => "+968",
                "latitude" => 21.512583,
                "longitude" => 55.923255,
            ],
            [
                "code" => "PK",
                "name" => "Pakistan",
                "phone_code" => "+92",
                "latitude" => 30.375321,
                "longitude" => 69.345116,
            ],
            [
                "code" => "PW",
                "name" => "Palau",
                "phone_code" => "+680",
                "latitude" => 7.51498,
                "longitude" => 134.58252,
            ],
            [
                "code" => "PS",
                "name" => "Palestinian Territory, Occupied",
                "phone_code" => "+970",
                "latitude" => 31.952162,
                "longitude" => 35.233154,
            ],
            [
                "code" => "PA",
                "name" => "Panama",
                "phone_code" => "+507",
                "latitude" => 8.537981,
                "longitude" => -80.782127,
            ],
            [
                "code" => "PG",
                "name" => "Papua New Guinea",
                "phone_code" => "+675",
                "latitude" => -6.314993,
                "longitude" => 143.95555,
            ],
            [
                "code" => "PY",
                "name" => "Paraguay",
                "phone_code" => "+595",
                "latitude" => -23.442503,
                "longitude" => -58.443832,
            ],
            [
                "code" => "PE",
                "name" => "Peru",
                "phone_code" => "+51",
                "latitude" => -9.189967,
                "longitude" => -75.015152,
            ],
            [
                "code" => "PH",
                "name" => "Philippines",
                "phone_code" => "+63",
                "latitude" => 12.879721,
                "longitude" => 121.774017,
            ],
            [
                "code" => "PN",
                "name" => "Pitcairn",
                "phone_code" => "+872",
                "latitude" => -24.703615,
                "longitude" => -127.439308,
            ],
            [
                "code" => "PL",
                "name" => "Poland",
                "phone_code" => "+48",
                "latitude" => 51.919438,
                "longitude" => 19.145136,
            ],
            [
                "code" => "PT",
                "name" => "Portugal",
                "phone_code" => "+351",
                "latitude" => 39.399872,
                "longitude" => -8.224454,
            ],
            [
                "code" => "PR",
                "name" => "Puerto Rico",
                "phone_code" => "+1939",
                "latitude" => 18.220833,
                "longitude" => -66.590149,
            ],
            [
                "code" => "QA",
                "name" => "Qatar",
                "phone_code" => "+974",
                "latitude" => 25.354826,
                "longitude" => 51.183884,
            ],
            [
                "code" => "RO",
                "name" => "Romania",
                "phone_code" => "+40",
                "latitude" => 45.943161,
                "longitude" => 24.96676,
            ],
            [
                "code" => "RU",
                "name" => "Russia",
                "phone_code" => "+7",
                "latitude" => 61.52401,
                "longitude" => 105.318756,
            ],
            [
                "code" => "RW",
                "name" => "Rwanda",
                "phone_code" => "+250",
                "latitude" => -1.940278,
                "longitude" => 29.873888,
            ],
            [
                "code" => "RE",
                "name" => "Reunion",
                "phone_code" => "+262",
                "latitude" => -21.115141,
                "longitude" => 55.536384,
            ],
            [
                "code" => "BL",
                "name" => "Saint Barthelemy",
                "phone_code" => "+590",
                "latitude" => 17.9000,
                "longitude" => 62.8333,
            ],
            [
                "code" => "SH",
                "name" => "Saint Helena, Ascension and Tristan Da Cunha",
                "phone_code" => "+290",
                "latitude" => -24.143474,
                "longitude" => -10.030696,
            ],
            [
                "code" => "KN",
                "name" => "Saint Kitts and Nevis",
                "phone_code" => "+1869",
                "latitude" => 17.357822,
                "longitude" => -62.782998,
            ],
            [
                "code" => "LC",
                "name" => "Saint Lucia",
                "phone_code" => "+1758",
                "latitude" => 13.909444,
                "longitude" => -60.978893,
            ],
            [
                "code" => "MF",
                "name" => "Saint Martin",
                "phone_code" => "+590",
                "latitude" => 0,
                "longitude" => 0,
            ],
            [
                "code" => "PM",
                "name" => "Saint Pierre and Miquelon",
                "phone_code" => "+508",
                "latitude" => 46.941936,
                "longitude" => -56.27111,
            ],
            [
                "code" => "VC",
                "name" => "Saint Vincent and the Grenadines",
                "phone_code" => "+1784",
                "latitude" => 12.984305,
                "longitude" => -61.287228,
            ],
            [
                "code" => "WS",
                "name" => "Samoa",
                "phone_code" => "+685",
                "latitude" => -13.759029,
                "longitude" => -172.104629,
            ],
            [
                "code" => "SM",
                "name" => "San Marino",
                "phone_code" => "+378",
                "latitude" => 43.94236,
                "longitude" => 12.457777,
            ],
            [
                "code" => "ST",
                "name" => "Sao Tome and Principe",
                "phone_code" => "+239",
                "latitude" => 0.18636,
                "longitude" => 6.613081,
            ],
            [
                "code" => "SA",
                "name" => "Saudi Arabia",
                "phone_code" => "+966",
                "latitude" => 23.885942,
                "longitude" => 45.079162,
            ],
            [
                "code" => "SN",
                "name" => "Senegal",
                "phone_code" => "+221",
                "latitude" => 14.497401,
                "longitude" => -14.452362,
            ],
            [
                "code" => "RS",
                "name" => "Serbia",
                "phone_code" => "+381",
                "latitude" => 44.016521,
                "longitude" => 21.005859,
            ],
            [
                "code" => "SC",
                "name" => "Seychelles",
                "phone_code" => "+248",
                "latitude" => -4.679574,
                "longitude" => 55.491977,
            ],
            [
                "code" => "SL",
                "name" => "Sierra Leone",
                "phone_code" => "+232",
                "latitude" => 8.460555,
                "longitude" => -11.779889,
            ],
            [
                "code" => "SG",
                "name" => "Singapore",
                "phone_code" => "+65",
                "latitude" => 1.352083,
                "longitude" => 103.819836,
            ],
            [
                "code" => "SK",
                "name" => "Slovakia",
                "phone_code" => "+421",
                "latitude" => 48.669026,
                "longitude" => 19.699024,
            ],
            [
                "code" => "SI",
                "name" => "Slovenia",
                "phone_code" => "+386",
                "latitude" => 46.151241,
                "longitude" => 14.995463,
            ],
            [
                "code" => "SB",
                "name" => "Solomon Islands",
                "phone_code" => "+677",
                "latitude" => -9.64571,
                "longitude" => 160.156194,
            ],
            [
                "code" => "SO",
                "name" => "Somalia",
                "phone_code" => "+252",
                "latitude" => 5.152149,
                "longitude" => 46.199616,
            ],
            [
                "code" => "ZA",
                "name" => "South Africa",
                "phone_code" => "+27",
                "latitude" => -30.559482,
                "longitude" => 22.937506,
            ],
            [
                "code" => "SS",
                "name" => "South Sudan",
                "phone_code" => "+211",
                "latitude" => 0,
                "longitude" => 0,
            ],
            [
                "code" => "GS",
                "name" => "South Georgia and the South Sandwich Islands",
                "phone_code" => "+500",
                "latitude" => -54.429579,
                "longitude" => -36.587909,
            ],
            [
                "code" => "ES",
                "name" => "Spain",
                "phone_code" => "+34",
                "latitude" => 40.463667,
                "longitude" => -3.74922,
            ],
            [
                "code" => "LK",
                "name" => "Sri Lanka",
                "phone_code" => "+94",
                "latitude" => 7.873054,
                "longitude" => 80.771797,
            ],
            [
                "code" => "SD",
                "name" => "Sudan",
                "phone_code" => "+249",
                "latitude" => 12.862807,
                "longitude" => 30.217636,
            ],
            [
                "code" => "SR",
                "name" => "Suriname",
                "phone_code" => "+597",
                "latitude" => 3.919305,
                "longitude" => -56.027783,
            ],
            [
                "code" => "SJ",
                "name" => "Svalbard and Jan Mayen",
                "phone_code" => "+47",
                "latitude" => 77.553604,
                "longitude" => 23.670272,
            ],
            [
                "code" => "SZ",
                "name" => "Swaziland",
                "phone_code" => "+268",
                "latitude" => -26.522503,
                "longitude" => 31.465866,
            ],
            [
                "code" => "SE",
                "name" => "Sweden",
                "phone_code" => "+46",
                "latitude" => 60.128161,
                "longitude" => 18.643501,
            ],
            [
                "code" => "CH",
                "name" => "Switzerland",
                "phone_code" => "+41",
                "latitude" => 46.818188,
                "longitude" => 8.227512,
            ],
            [
                "code" => "SY",
                "name" => "Syrian Arab Republic",
                "phone_code" => "+963",
                "latitude" => 34.802075,
                "longitude" => 38.996815,
            ],
            [
                "code" => "TW",
                "name" => "Taiwan",
                "phone_code" => "+886",
                "latitude" => 23.69781,
                "longitude" => 120.960515,
            ],
            [
                "code" => "TJ",
                "name" => "Tajikistan",
                "phone_code" => "+992",
                "latitude" => 38.861034,
                "longitude" => 71.276093,
            ],
            [
                "code" => "TZ",
                "name" => "Tanzania, United Republic of Tanzania",
                "phone_code" => "+255",
                "latitude" => -6.369028,
                "longitude" => 34.888822,
            ],
            [
                "code" => "TH",
                "name" => "Thailand",
                "phone_code" => "+66",
                "latitude" => 15.870032,
                "longitude" => 100.992541,
            ],
            [
                "code" => "TL",
                "name" => "Timor-Leste",
                "phone_code" => "+670",
                "latitude" => -8.874217,
                "longitude" => 125.727539,
            ],
            [
                "code" => "TG",
                "name" => "Togo",
                "phone_code" => "+228",
                "latitude" => 8.619543,
                "longitude" => 0.824782,
            ],
            [
                "code" => "TK",
                "name" => "Tokelau",
                "phone_code" => "+690",
                "latitude" => -8.967363,
                "longitude" => -171.855881,
            ],
            [
                "code" => "TO",
                "name" => "Tonga",
                "phone_code" => "+676",
                "latitude" => -21.178986,
                "longitude" => -175.198242,
            ],
            [
                "code" => "TT",
                "name" => "Trinidad and Tobago",
                "phone_code" => "+1868",
                "latitude" => 10.691803,
                "longitude" => -61.222503,
            ],
            [
                "code" => "TN",
                "name" => "Tunisia",
                "phone_code" => "+216",
                "latitude" => 33.886917,
                "longitude" => 9.537499,
            ],
            [
                "code" => "TR",
                "name" => "Turkey",
                "phone_code" => "+90",
                "latitude" => 38.963745,
                "longitude" => 35.243322,
            ],
            [
                "code" => "TM",
                "name" => "Turkmenistan",
                "phone_code" => "+993",
                "latitude" => 38.969719,
                "longitude" => 59.556278,
            ],
            [
                "code" => "TC",
                "name" => "Turks and Caicos Islands",
                "phone_code" => "+1649",
                "latitude" => 21.694025,
                "longitude" => -71.797928,
            ],
            [
                "code" => "TV",
                "name" => "Tuvalu",
                "phone_code" => "+688",
                "latitude" => -7.109535,
                "longitude" => 177.64933,
            ],
            [
                "code" => "UG",
                "name" => "Uganda",
                "phone_code" => "+256",
                "latitude" => 1.373333,
                "longitude" => 32.290275,
            ],
            [
                "code" => "UA",
                "name" => "Ukraine",
                "phone_code" => "+380",
                "latitude" => 48.379433,
                "longitude" => 31.16558,
            ],
            [
                "code" => "AE",
                "name" => "United Arab Emirates",
                "phone_code" => "+971",
                "latitude" => 23.424076,
                "longitude" => 53.847818,
            ],
            [
                "code" => "GB",
                "name" => "United Kingdom",
                "phone_code" => "+44",
                "latitude" => 55.378051,
                "longitude" => -3.435973,
            ],
            [
                "code" => "US",
                "name" => "United States",
                "phone_code" => "+1",
                "latitude" => 37.09024,
                "longitude" => -95.712891,
            ],
            [
                "code" => "UY",
                "name" => "Uruguay",
                "phone_code" => "+598",
                "latitude" => -32.522779,
                "longitude" => -55.765835,
            ],
            [
                "code" => "UZ",
                "name" => "Uzbekistan",
                "phone_code" => "+998",
                "latitude" => 41.377491,
                "longitude" => 64.585262,
            ],
            [
                "code" => "VU",
                "name" => "Vanuatu",
                "phone_code" => "+678",
                "latitude" => -15.376706,
                "longitude" => 166.959158,
            ],
            [
                "code" => "VE",
                "name" => "Venezuela, Bolivarian Republic of Venezuela",
                "phone_code" => "+58",
                "latitude" => 6.42375,
                "longitude" => -66.58973,
            ],
            [
                "code" => "VN",
                "name" => "Vietnam",
                "phone_code" => "+84",
                "latitude" => 14.058324,
                "longitude" => 108.277199,
            ],
            [
                "code" => "VG",
                "name" => "Virgin Islands, British",
                "phone_code" => "+1284",
                "latitude" => 18.420695,
                "longitude" => -64.639968,
            ],
            [
                "code" => "VI",
                "name" => "Virgin Islands, U.S.",
                "phone_code" => "+1340",
                "latitude" => 18.335765,
                "longitude" => -64.896335,
            ],
            [
                "code" => "WF",
                "name" => "Wallis and Futuna",
                "phone_code" => "+681",
                "latitude" => -13.768752,
                "longitude" => -177.156097,
            ],
            [
                "code" => "YE",
                "name" => "Yemen",
                "phone_code" => "+967",
                "latitude" => 15.552727,
                "longitude" => 48.516388,
            ],
            [
                "code" => "ZM",
                "name" => "Zambia",
                "phone_code" => "+260",
                "latitude" => -13.133897,
                "longitude" => 27.849332,
            ],
            [
                "code" => "ZW",
                "name" => "Zimbabwe",
                "phone_code" => "+263",
                "latitude" => -19.015438,
                "longitude" => 29.154857,
            ],
        ];


        DB::table('countries')->insert($countries);
    }
}
