<?php

namespace Database\Seeders\Share;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {


        $timestamp = Carbon::now()->toDateTimeString();
        $countries = [
            ["code" => "AF", "name" => "Afghanistan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AL", "name" => "Albania", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "DZ", "name" => "Algeria", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "DS", "name" => "American Samoa", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AD", "name" => "Andorra", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AO", "name" => "Angola", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AI", "name" => "Anguilla", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AQ", "name" => "Antarctica", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AG", "name" => "Antigua and Barbuda", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AR", "name" => "Argentina", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AM", "name" => "Armenia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AW", "name" => "Aruba", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AU", "name" => "Australia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AT", "name" => "Austria", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AZ", "name" => "Azerbaijan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BS", "name" => "Bahamas", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BH", "name" => "Bahrain", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BD", "name" => "Bangladesh", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BB", "name" => "Barbados", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BY", "name" => "Belarus", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BE", "name" => "Belgium", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BZ", "name" => "Belize", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BJ", "name" => "Benin", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BM", "name" => "Bermuda", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BT", "name" => "Bhutan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BO", "name" => "Bolivia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BA", "name" => "Bosnia and Herzegovina", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BW", "name" => "Botswana", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BV", "name" => "Bouvet Island", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BR", "name" => "Brazil", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "IO", "name" => "British Indian Ocean Territory", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BN", "name" => "Brunei Darussalam", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BG", "name" => "Bulgaria", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BF", "name" => "Burkina Faso", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "BI", "name" => "Burundi", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KH", "name" => "Cambodia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CM", "name" => "Cameroon", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CA", "name" => "Canada", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CV", "name" => "Cape Verde", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KY", "name" => "Cayman Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CF", "name" => "Central African Republic", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TD", "name" => "Chad", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CL", "name" => "Chile", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CN", "name" => "China", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CX", "name" => "Christmas Island", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CC", "name" => "Cocos (Keeling) Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CO", "name" => "Colombia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KM", "name" => "Comoros", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CD", "name" => "Democratic Republic of the Congo", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CG", "name" => "Republic of the Congo", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CK", "name" => "Cook Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CR", "name" => "Costa Rica", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "HR", "name" => "Croatia (Hrvatska)", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CU", "name" => "Cuba", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CY", "name" => "Cyprus", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CZ", "name" => "Czech Republic", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "DK", "name" => "Denmark", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "DJ", "name" => "Djibouti", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "DM", "name" => "Dominica", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "DO", "name" => "Dominican Republic", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TP", "name" => "East Timor", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "EC", "name" => "Ecuador", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "EG", "name" => "Egypt", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SV", "name" => "El Salvador", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GQ", "name" => "Equatorial Guinea", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "ER", "name" => "Eritrea", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "EE", "name" => "Estonia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "ET", "name" => "Ethiopia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "FK", "name" => "Falkland Islands (Malvinas)", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "FO", "name" => "Faroe Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "FJ", "name" => "Fiji", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "FI", "name" => "Finland", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "FR", "name" => "France", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "FX", "name" => "France, Metropolitan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GF", "name" => "French Guiana", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PF", "name" => "French Polynesia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TF", "name" => "French Southern Territories", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GA", "name" => "Gabon", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GM", "name" => "Gambia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GE", "name" => "Georgia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "DE", "name" => "Germany", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GH", "name" => "Ghana", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GI", "name" => "Gibraltar", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GK", "name" => "Guernsey", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GR", "name" => "Greece", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GL", "name" => "Greenland", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GD", "name" => "Grenada", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GP", "name" => "Guadeloupe", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GU", "name" => "Guam", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GT", "name" => "Guatemala", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GN", "name" => "Guinea", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GW", "name" => "Guinea-Bissau", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GY", "name" => "Guyana", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "HT", "name" => "Haiti", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "HM", "name" => "Heard and Mc Donald Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "HN", "name" => "Honduras", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "HK", "name" => "Hong Kong", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "HU", "name" => "Hungary", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "IS", "name" => "Iceland", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "IN", "name" => "India", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "IM", "name" => "Isle of Man", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "ID", "name" => "Indonesia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "IR", "name" => "Iran (Islamic Republic of)", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "IQ", "name" => "Iraq", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "IE", "name" => "Ireland", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "IL", "name" => "Israel", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "IT", "name" => "Italy", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CI", "name" => "Ivory Coast", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "JE", "name" => "Jersey", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "JM", "name" => "Jamaica", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "JP", "name" => "Japan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "JO", "name" => "Jordan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KZ", "name" => "Kazakhstan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KE", "name" => "Kenya", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KI", "name" => "Kiribati", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KP", "name" => "Korea, Democratic People's Republic of", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KR", "name" => "Korea, Republic of", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "XK", "name" => "Kosovo", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KW", "name" => "Kuwait", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KG", "name" => "Kyrgyzstan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LA", "name" => "Lao People's Democratic Republic", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LV", "name" => "Latvia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LB", "name" => "Lebanon", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LS", "name" => "Lesotho", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LR", "name" => "Liberia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LY", "name" => "Libyan Arab Jamahiriya", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LI", "name" => "Liechtenstein", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LT", "name" => "Lithuania", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LU", "name" => "Luxembourg", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MO", "name" => "Macau", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MK", "name" => "North Macedonia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MG", "name" => "Madagascar", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MW", "name" => "Malawi", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MY", "name" => "Malaysia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MV", "name" => "Maldives", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "ML", "name" => "Mali", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MT", "name" => "Malta", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MH", "name" => "Marshall Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MQ", "name" => "Martinique", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MR", "name" => "Mauritania", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MU", "name" => "Mauritius", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TY", "name" => "Mayotte", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MX", "name" => "Mexico", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "FM", "name" => "Micronesia, Federated States of", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MD", "name" => "Moldova, Republic of", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MC", "name" => "Monaco", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MN", "name" => "Mongolia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "ME", "name" => "Montenegro", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MS", "name" => "Montserrat", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MA", "name" => "Morocco", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MZ", "name" => "Mozambique", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MM", "name" => "Myanmar", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NA", "name" => "Namibia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NR", "name" => "Nauru", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NP", "name" => "Nepal", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NL", "name" => "Netherlands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AN", "name" => "Netherlands Antilles", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NC", "name" => "New Caledonia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NZ", "name" => "New Zealand", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NI", "name" => "Nicaragua", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NE", "name" => "Niger", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NG", "name" => "Nigeria", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NU", "name" => "Niue", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NF", "name" => "Norfolk Island", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "MP", "name" => "Northern Mariana Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "NO", "name" => "Norway", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "OM", "name" => "Oman", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PK", "name" => "Pakistan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PW", "name" => "Palau", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PS", "name" => "Palestine", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PA", "name" => "Panama", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PG", "name" => "Papua New Guinea", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PY", "name" => "Paraguay", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PE", "name" => "Peru", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PH", "name" => "Philippines", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PN", "name" => "Pitcairn", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PL", "name" => "Poland", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PT", "name" => "Portugal", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PR", "name" => "Puerto Rico", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "QA", "name" => "Qatar", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "RE", "name" => "Reunion", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "RO", "name" => "Romania", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "RU", "name" => "Russian Federation", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "RW", "name" => "Rwanda", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "KN", "name" => "Saint Kitts and Nevis", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LC", "name" => "Saint Lucia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "VC", "name" => "Saint Vincent and the Grenadines", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "WS", "name" => "Samoa", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SM", "name" => "San Marino", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "ST", "name" => "Sao Tome and Principe", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SA", "name" => "Saudi Arabia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SN", "name" => "Senegal", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "RS", "name" => "Serbia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SC", "name" => "Seychelles", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SL", "name" => "Sierra Leone", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SG", "name" => "Singapore", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SK", "name" => "Slovakia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SI", "name" => "Slovenia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SB", "name" => "Solomon Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SO", "name" => "Somalia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "ZA", "name" => "South Africa", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GS", "name" => "South Georgia South Sandwich Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SS", "name" => "South Sudan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "ES", "name" => "Spain", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "LK", "name" => "Sri Lanka", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SH", "name" => "St. Helena", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "PM", "name" => "St. Pierre and Miquelon", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SD", "name" => "Sudan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SR", "name" => "Suriname", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SJ", "name" => "Svalbard and Jan Mayen Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SZ", "name" => "Eswatini", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SE", "name" => "Sweden", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "CH", "name" => "Switzerland", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "SY", "name" => "Syrian Arab Republic", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TW", "name" => "Taiwan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TJ", "name" => "Tajikistan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TZ", "name" => "Tanzania, United Republic of", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TH", "name" => "Thailand", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TG", "name" => "Togo", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TK", "name" => "Tokelau", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TO", "name" => "Tonga", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TT", "name" => "Trinidad and Tobago", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TN", "name" => "Tunisia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TR", "name" => "Turkey", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TM", "name" => "Turkmenistan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TC", "name" => "Turks and Caicos Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "TV", "name" => "Tuvalu", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "UG", "name" => "Uganda", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "UA", "name" => "Ukraine", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "AE", "name" => "United Arab Emirates", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "GB", "name" => "United Kingdom", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "US", "name" => "United States", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "UM", "name" => "United States minor outlying islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "UY", "name" => "Uruguay", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "UZ", "name" => "Uzbekistan", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "VU", "name" => "Vanuatu", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "VA", "name" => "Vatican City State", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "VE", "name" => "Venezuela", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "VN", "name" => "Vietnam", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "VG", "name" => "Virgin Islands (British)", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "VI", "name" => "Virgin Islands (U.S.)", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "WF", "name" => "Wallis and Futuna Islands", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "EH", "name" => "Western Sahara", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "YE", "name" => "Yemen", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "ZM", "name" => "Zambia", "created_at"=>$timestamp,"updated_at"=>$timestamp],
            ["code" => "ZW", "name" => "Zimbabwe", "created_at"=>$timestamp,"updated_at"=>$timestamp]
        ];

        DB::table('countries')->insert($countries);
    }
}
